replicas: 1
serviceAccountPrivateKey: ""
kubernetesCAKey: ""
rootCACertificate: ""
kubernetesCACertificate: ""
apiServers: []
flexVolumePluginDir: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
kubeScheduler:
  image: ""
kubeControllerManager:
  image: ""
haproxyImage: "haproxy:3.3.1-alpine"
